### PR TITLE
Fix: Missing Anchor tag

### PR DESCRIPTION
**Pull request by sharansudheer**
In the footer, a set of anchor tags with the target as blank was needed to be added to enhance UX

### CODE REVIEW

**Comment by sharansudheer** [comment]
I haven't touched any other files, something has happened for the good in the other 2 files.

**Comment by 0VERRIDER** [comment]
> I haven't touched any other files, something has happened for the good in the other 2 files.

Well I guess The best practice is to replace the whole `<Link>` with `<a> ` Since I want the social links to open in externally, not within.

Once again I apologize the bad practices through out the project.

**Review by 0VERRIDER — CHANGES_REQUESTED** [review]
Instead of using `<Link>` and `<a>` together we will just use the anchor tag alone since we are going to an external website there.

**Comment by sharansudheer** [comment]
Ok, I'll add the requested changes in the main overhaul 😁.

**Pull request closed without merging**
